### ISSUE TITLE
Install with Visual Studio build doesn't install the "Release" folder

### ISSUE THREAD

**Issue by jhughes-mw** [mathworks/libmexclass#10]
See this snippit from the install:

install/libmexclass/Release/gateway.exp
install/libmexclass/Release/gateway.lib
install/libmexclass/Release/gateway.mexw64
install/libmexclass/Release/mexclass.dll
install/libmexclass/Release/mexclass.exp
install/libmexclass/Release/mexclass.lib

The extra "Release" folder isn't accounted for.

**Comment by sreeharihegden** [comment]
This gets resolved by #41 as we package the necessary binaries along with the MATLAB source into `+libmexclass/+proxy` on all platforms.

Marking as a duplicate of #28.
